small-projects/vidly/movies/urls.py
# list objects that maps urlsurl endpoints to our view function

from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    # pass a refercne to the funtion
    path('', views.index, name='index'),
    path('<int:movie_id>', views.detail, name='detail')
]

small-projects/vidly/vidly/urls.py
from django.contrib import admin
from django.urls import path, include
from api.models import MovieResource
from . import views

movie_resource = MovieResource()


urlpatterns = [
    path('', views.home),
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('api/', include(movie_resource.urls))
]

small-projects/vidly/api/models.py
from django.db import models
from tastypie.resources import ModelResource
from movies.models import Movie

# Create your models here.


class MovieResource(ModelResource):
    class Meta:
        queryset = Movie.objects.all()
        resource_name = 'movies'
        excludes = ['date_created',]

small-projects/vidly/movies/models.py
from django.db import models
from django.utils import timezone

# Create your models here.


class Genre(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Movie(models.Model):
    title = models.CharField(max_length=255)
    release_year = models.IntegerField()
    number_in_stock = models.IntegerField()
    daily_rate = models.FloatField()
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)
    date_created = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title


# now tell djngo to syncrozie our databse with the models we defined

small-projects/vidly/api/views.py
from django.shortcuts import render

# Create your views here.

small-projects/vidly/movies/views.py
from django.http import HttpResponse, Http404
from django.shortcuts import render, get_object_or_404
from .models import Movie

# pipenv install pylint-django

# Create your views here.


def index(request):
    # Movie.objects.all()
    # Movie.objects.filter(release_year=1988)
    # Movie.objects.get(id=1)

    movies = Movie.objects.all()

    # output = ','.join([m.title for m in movies])
    # return HttpResponse("Hello World!")  # map this to a url
    # return HttpResponse(output)

    return render(request, 'movies/index.html', {"movies": movies})


def detail(request, movie_id):
    # try:
    #     movie = Movie.objects.get(pk=movie_id)
    #     return render(request, 'movies/detail.html', {'movie': movie})
    # except Movie.DoesNotExist:
    #     raise Http404
    movie = get_object_or_404(Movie, pk=movie_id)
    return render(request, 'movies/detail.html', {'movie': movie})

small-projects/vidly/vidly/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'home.html')

small-projects/vidly/movies/templates/movies/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4Q6Gf2aSP4eDXB8Miphtr37CMZZQ5oXLH2yaXMJ2w8e2ZtHTl7GptT4jmndRuHDT" crossorigin="anonymous">
  </head>
  <body>
    {% block content %}
    
    {% endblock  %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/js/bootstrap.bundle.min.js" integrity="sha384-j1CDi7MgGQ12Z7Qab0qlWQ/Qqz24Gc6BM0thvEMVjHnfYGF0rmFCozFSxQBxwHKO" crossorigin="anonymous"></script>
  </body>
</html>

small-projects/vidly/movies/templates/movies/detail.html
{% extends "base.html" %}

{% block content %}
    <dl>
        <dt>Title</dt>
        <dd>{{movie.title}}</dd>
        <dt>Genre</dt>
        <dd>{{movie.genre}}</dd>
        <dt>Stock</dt>
        <dd>{{movie.number_in_stock}}</dd>
    </dl>
{% endblock  %}

small-projects/vidly/movies/templates/movies/index.html
{% extends "base.html" %}
{% block content %}

    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>Title</th>
                <th>Genre</th>
                <th>Stock</th>
                <th>Daily Rate</th>
            </tr>
        </thead>
        <tbody>
            {% for movie in movies %}
                <tr>
                    <td>
                        {% comment %} <a href="{{ movie.id }}">{{ movie.title}}</a> {% endcomment %}
                        <a href="{% url 'movies:detail' movie.id %}">{{ movie.title}}</a>
                    </td>
                    <td>{{movie.genre}}</td>
                    <td>{{movie.number_in_stock}}</td>
                    <td>{{movie.daily_rate}}</td>
                </tr>
            {% endfor %}
            
        </tbody>
    </table>
{% endblock  %}

small-projects/vidly/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4Q6Gf2aSP4eDXB8Miphtr37CMZZQ5oXLH2yaXMJ2w8e2ZtHTl7GptT4jmndRuHDT" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar bg-body-tertiary">
      <div class="container-fluid">
      <a class="navbar-brand" href="#">Vidly</a>
      </div>
    </nav>
    <main class="container">
      {% block content %}
    
      {% endblock  %}
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/js/bootstrap.bundle.min.js" integrity="sha384-j1CDi7MgGQ12Z7Qab0qlWQ/Qqz24Gc6BM0thvEMVjHnfYGF0rmFCozFSxQBxwHKO" crossorigin="anonymous"></script>
  </body>
</html>

small-projects/vidly/templates/home.html
{% extends "base.html" %}


{% block content %}
    <a href="{% url 'movies:index' %}">Movies<a/>
    

{% endblock  %}